kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # NodePort the frontend Service will use
        hostPort: 30080        # reachable at http://localhost:30080
        protocol: TCP
